name: "Docker Socket Proxy"
description: "Proxy over your Docker socket to a port. Configure which Docker API sections are accessible by enabling/disabling the options below. Each option controls access to a specific API endpoint."
version: "1.2.0"
slug: "ha-docker-socket-proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  2375/tcp: 2375
ports_description:
  2375/tcp: Proxy port for Docker API
docker_api: true
full_access: true
url: https://github.com/rikardronnkvist/ha-docker-socket-proxy


options:
  ALLOW_RESTARTS: false
  ALLOW_STOP: false
  ALLOW_START: false
  AUTH: false
  BUILD: true
  COMMIT: true
  CONFIGS: true
  CONTAINERS: true
  DISABLE_IPV6: false
  DISTRIBUTION: true
  EVENTS: true
  EXEC: false
  GRPC: false
  IMAGES: true
  INFO: true
  LOG_LEVEL: "info"
  NETWORKS: true
  NODES: true
  PING: true
  PLUGINS: true
  POST: false
  SECRETS: false
  SERVICES: true
  SESSION: true
  SOCKET_PATH: "/var/run/docker.sock"
  SWARM: true
  SYSTEM: true
  TASKS: false
  VERSION: true
  VOLUMES: true

schema:
  ALLOW_RESTARTS: bool
  ALLOW_STOP: bool
  ALLOW_START: bool
  AUTH: bool
  BUILD: bool
  COMMIT: bool
  CONFIGS: bool
  CONTAINERS: bool
  DISABLE_IPV6: bool
  DISTRIBUTION: bool
  EVENTS: bool
  EXEC: bool
  GRPC: bool
  IMAGES: bool
  INFO: bool
  LOG_LEVEL: list(debug|info|notice|warning|error|critical|alert|emergency)
  NETWORKS: bool
  NODES: bool
  PING: bool
  PLUGINS: bool
  POST: bool
  SECRETS: bool
  SERVICES: bool
  SESSION: bool
  SOCKET_PATH: str
  SWARM: bool
  SYSTEM: bool
  TASKS: bool
  VERSION: bool
  VOLUMES: bool